### ISSUE TITLE
Request data collection doesn't work in Flask 0.9

### ISSUE THREAD

**Issue by brianr** [rollbar/pyrollbar#59]
In Flask 0.9, the call to `request.get_json()` fails, causing the request data to not be attached. Exception is like this:

```
ERROR:rollbar:Exception while building request_data for Rollbar payload: AttributeError("'Request' object has no attribute 'get_json'",)
Traceback (most recent call last):
  File "/venv/lib/python2.7/site-packages/rollbar/__init__.py", line 759, in _add_request_data
    request_data = _build_request_data(request)
  File "/venv/lib/python2.7/site-packages/rollbar/__init__.py", line 802, in _build_request_data
    return _build_werkzeug_request_data(actual_request)
  File "/venv/lib/python2.7/site-packages/rollbar/__init__.py", line 981, in _build_werkzeug_request_data
    if request.get_json():
AttributeError: 'Request' object has no attribute 'get_json'
```

Might be able to fix by calling `request.json()` instead; need to double-check compatibility.

**Comment by philfreo** [comment]
I think you mean `request.json` instead of `request.json()`
